/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unileao.telas;

/**
 *
 * @author Shayron
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Painel = new javax.swing.JLabel();
        caixa_De_Botao = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Cadastrar_Cliente = new javax.swing.JButton();
        Cadastrar_Funcionario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_Painel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Text_Painel.setText("Painel");
        getContentPane().add(Text_Painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, 40));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Cadastrar_Cliente.setText("Cadastro de Clientes");
        Cadastrar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_ClienteActionPerformed(evt);
            }
        });

        Cadastrar_Funcionario.setText("Cadastrar Funcionário");
        Cadastrar_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout caixa_De_BotaoLayout = new javax.swing.GroupLayout(caixa_De_Botao);
        caixa_De_Botao.setLayout(caixa_De_BotaoLayout);
        caixa_De_BotaoLayout.setHorizontalGroup(
            caixa_De_BotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixa_De_BotaoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Home)
                .addGap(67, 67, 67)
                .addComponent(Cadastrar_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Cadastrar_Funcionario)
                .addContainerGap())
        );
        caixa_De_BotaoLayout.setVerticalGroup(
            caixa_De_BotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixa_De_BotaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caixa_De_BotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home)
                    .addComponent(Cadastrar_Cliente)
                    .addComponent(Cadastrar_Funcionario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(caixa_De_Botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 530, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 660, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_ClienteActionPerformed
       cadastrarCliente cadastrarCliente = new cadastrarCliente();
       cadastrarCliente.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Cadastrar_ClienteActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
       TelaPrincipal TelaPrincipal = new TelaPrincipal();
TelaPrincipal.setVisibe(true);
this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void Cadastrar_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_FuncionarioActionPerformed
       cadastrarFuncionario cadastrarFuncionario = new cadastrarFuncionario();
       cadastrarFuncionario.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Cadastrar_FuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar_Cliente;
    private javax.swing.JButton Cadastrar_Funcionario;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Text_Painel;
    private javax.swing.JPanel caixa_De_Botao;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    void setVisibe(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
}
